name: Build Stockfish x86-64

on:
  workflow_dispatch:

jobs:
  build-x86-64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt update && sudo apt install -y g++ make

      - name: Build stockfish (x86-64)
        run: |
          cd src
          make build ARCH=x86-64

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: stockfish-x86-64
          path: src/stockfish
